package services

import (
	"kahoot-game/internal/models"
	"math/rand"
	"time"
)

// TwoTypesQuestion 2種人題目結構
type TwoTypesQuestion struct {
	Category string `json:"category"`
	Question string `json:"question"`
	OptionA  string `json:"optionA"`
	OptionB  string `json:"optionB"`
}

// GetTwoTypesQuestions 獲取「2種人」題庫
func GetTwoTypesQuestions() []TwoTypesQuestion {
	return []TwoTypesQuestion{
		// 飲食爭議類
		{Category: "food", Question: "世界上只有兩種人", OptionA: "魯肉飯一定要拌勻", OptionB: "魯肉飯要分層吃"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "Pizza可以加鳳梨", OptionB: "Pizza加鳳梨是邪教"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "臭豆腐要吃炸的", OptionB: "臭豆腐要吃滷的"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "麵食主義者", OptionB: "米食主義者"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "義大利麵用叉子", OptionB: "義大利麵用筷子"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "珍奶一定要去冰", OptionB: "珍奶正常冰才對"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "火鍋蛋餃要咬破", OptionB: "火鍋蛋餃整顆吃"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃泡麵一定要加蛋", OptionB: "泡麵原味最純正"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "湯圓要鹹的", OptionB: "湯圓要甜的"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "粽子一定要甜粽", OptionB: "粽子就是要鹹粽"},
		
		// 生活習慣類
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "牙膏從底部擠", OptionB: "牙膏從中間擠"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "洗澡先洗頭", OptionB: "洗澡先洗身體"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "睡覺一定要關燈", OptionB: "睡覺要留小夜燈"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "起床立刻摺棉被", OptionB: "棉被隨便鋪就好"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "衣服要摺得整齊", OptionB: "衣服掛著就好"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "馬桶蓋一定要蓋", OptionB: "馬桶蓋開著無所謂"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "鞋子進門要排好", OptionB: "鞋子脫了就算了"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "冷氣要開到很冷", OptionB: "冷氣適中就好"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "手機電量低於50%就充", OptionB: "手機用到10%以下才充"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "桌面一定要整齊", OptionB: "桌面亂一點沒關係"},
		
		// 個性偏好類
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡計劃一切", OptionB: "喜歡隨機應變"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "早起的鳥兒", OptionB: "夜貓子類型"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "內向安靜型", OptionB: "外向活潑型"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "完美主義者", OptionB: "差不多就好派"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡獨處", OptionB: "喜歡熱鬧"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "理性思考派", OptionB: "感性直覺派"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "謹慎保守型", OptionB: "冒險創新型"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡競爭", OptionB: "喜歡合作"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "重視過程", OptionB: "重視結果"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "樂觀正向派", OptionB: "現實謹慎派"},
		
		// 科技使用類
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "iPhone派", OptionB: "Android派"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "Mac用戶", OptionB: "PC用戶"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "Chrome瀏覽器", OptionB: "Safari瀏覽器"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "社群媒體重度用戶", OptionB: "社群媒體輕度用戶"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "喜歡最新科技", OptionB: "喜歡穩定舊版"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "線上購物派", OptionB: "實體店面派"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "數位支付派", OptionB: "現金支付派"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "雲端存檔派", OptionB: "本機存檔派"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "自動更新派", OptionB: "手動更新派"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "深色模式愛好者", OptionB: "淺色模式愛好者"},
		
		// 娛樂休閒類
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "電影院派", OptionB: "在家看片派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "書籍閱讀派", OptionB: "影片觀看派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "戶外活動派", OptionB: "室內活動派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "音樂派", OptionB: "Podcast派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "遊戲玩家", OptionB: "非遊戲玩家"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "旅遊冒險派", OptionB: "居家休息派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "運動健身派", OptionB: "靜態休閒派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "追劇狂熱派", OptionB: "偶爾看片派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "聚會社交派", OptionB: "宅在家派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "早睡早起派", OptionB: "熬夜晚睡派"},

		// --- 擴充開始 (51-200) ---
		// 飲食類
		{Category: "food", Question: "世界上只有兩種人", OptionA: "可樂加冰塊", OptionB: "可樂不加冰"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "薯條沾糖醋醬", OptionB: "薯條沾番茄醬"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "漢堡層層吃", OptionB: "漢堡一口咬"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "咖啡加糖加奶", OptionB: "只喝黑咖啡"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "雞排要切", OptionB: "雞排不切"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "火鍋先下肉", OptionB: "火鍋先下菜"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "咖哩飯拌開", OptionB: "咖哩飯不拌"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "水餃沾醬油", OptionB: "水餃沾白醋"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "牛排吃全熟", OptionB: "牛排吃五分熟"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "皮蛋豆腐拌碎", OptionB: "皮蛋豆腐完整吃"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "鹹酥雞加辣", OptionB: "鹹酥雞不加辣"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吐司去邊", OptionB: "吐司留邊"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "剉冰攪拌派", OptionB: "剉冰挖著吃派"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "喝湯要熱騰騰", OptionB: "湯溫溫的就好"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "西瓜加鹽巴", OptionB: "西瓜直接吃"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "茶包泡很久", OptionB: "茶包快速拿走"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "煎餃沾辣醬", OptionB: "煎餃沾蒜泥"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "布丁挖著吃", OptionB: "布丁倒出來吃"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "豆漿加糖", OptionB: "豆漿喝無糖"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "便當先吃排骨", OptionB: "排骨留到最後吃"},

		// 生活習慣類
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "出門必帶傘", OptionB: "淋雨也沒關係"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "鬧鐘響一次就起", OptionB: "鬧鐘設定十個"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "看書用書籤", OptionB: "直接摺角"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "筆寫到沒水才丟", OptionB: "不見了才換"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "衛生紙順著抽", OptionB: "衛生紙逆著抽"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "洗澡喜歡熱水", OptionB: "洗澡喜歡溫水"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "耳機線整齊捲", OptionB: "隨便塞口袋"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "回家先換衣服", OptionB: "回家直接躺沙發"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "指甲留很短", OptionB: "指甲會修形狀"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "東西壞了自己修", OptionB: "東西壞了直接換"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "睡覺穿睡衣", OptionB: "睡覺隨便穿"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "習慣用手寫筆記", OptionB: "習慣數位筆記"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "走路很快", OptionB: "走路慢條斯理"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "皮夾隨便塞錢", OptionB: "錢鈔要照面額排"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "傘乾了才收", OptionB: "溼答答就捆起來"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "鑰匙掛在門口", OptionB: "鑰匙隨便放"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "喜歡喝氣泡水", OptionB: "只喝純水"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "睡覺一定要枕頭", OptionB: "沒枕頭也能睡"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "東西過期立刻丟", OptionB: "聞一聞沒壞繼續吃"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "買東西看標價", OptionB: "買東西看感覺"},

		// 科技與數位類
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "分頁開超多", OptionB: "看完立刻關分頁"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "手機套要防摔", OptionB: "手機裸機派"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "通知紅點必消", OptionB: "累積幾千則無視"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "鍵盤機械軸", OptionB: "薄膜鍵盤"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "螢幕亮度最亮", OptionB: "螢幕亮度偏暗"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "用滑鼠", OptionB: "用觸控板"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "密碼每一組都一樣", OptionB: "每一組都不一樣"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "視訊會開鏡頭", OptionB: "視訊堅持不開"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "打字用注音", OptionB: "打字用拼音或倉頡"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "電子書愛好者", OptionB: "實體書擁護者"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "照片拍一張就夠", OptionB: "同場景連拍百張"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "電腦從不關機", OptionB: "沒在使用就關機"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "習慣用 Google 搜尋", OptionB: "喜歡問 ChatGPT"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "桌面圖示排滿滿", OptionB: "桌面空空如也"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "通訊軟體用語音", OptionB: "堅持傳文字"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "充電線隨便插", OptionB: "充電線要收納整齊"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "網購看負評", OptionB: "網購看銷量"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "用手錶看時間", OptionB: "用手機看時間"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "喜歡藍牙耳機", OptionB: "喜歡有線耳機"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "備份狂人", OptionB: "檔案隨機遺失派"},

		// 個性與心智類
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "出門前查地圖", OptionB: "邊走邊看地標"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "購物清單派", OptionB: "隨興選購派"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "餐廳先看評價", OptionB: "路過順眼就進去"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "訊息秒回派", OptionB: "想好久才回派"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡看恐怖片", OptionB: "看到鬼片就轉台"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "相信星座命理", OptionB: "堅定不信派"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "禮物現場拆", OptionB: "回家偷偷拆"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "錢包只放必要卡片", OptionB: "錢包塞滿發票收據"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡聽新歌", OptionB: "老歌循環播放"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "對發票必中獎", OptionB: "兩年沒中過半張"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡自拍", OptionB: "拍照手遮臉"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "旅行排細節日程", OptionB: "到當地再想去哪"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "錢花在體驗上", OptionB: "錢花在物質上"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "社交恐懼症", OptionB: "社交花蝴蝶"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡大自然", OptionB: "更愛都市繁華"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "遇到問題先查 Google", OptionB: "遇到問題先問人"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "早退是為了休息", OptionB: "加班是為了效率"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡貓派", OptionB: "喜歡狗派"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "說話直說", OptionB: "說話拐彎抹角"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "很愛開玩笑", OptionB: "性格嚴肅"},

		// 工作與效率類 (新增)
		{Category: "work", Question: "世界上只有兩種人", OptionA: "準時完成任務", OptionB: "最後一刻才動手"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "喜歡團隊合作", OptionB: "單打獨鬥比較快"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "開會要寫記錄", OptionB: "聽過就好懶得記"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "工作時要聽音樂", OptionB: "工作時需要極度安靜"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "電腦桌面清空", OptionB: "桌面全是檔案"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "回郵件像打仗", OptionB: "回郵件像創作"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "喜歡視訊開會", OptionB: "偏好文字報備"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "會設定每日代辦", OptionB: "隨波逐流派"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "午休一定要睡", OptionB: "午休不用睡覺"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "喜歡辦公室氣氛", OptionB: "遠端工作愛好者"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "主動解決問題", OptionB: "等長官指示"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "報告做得美美的", OptionB: "內容實在不看包裝"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "提早十分鐘到", OptionB: "最後三十秒滑進位子"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "喜歡挑戰新技術", OptionB: "穩定壓倒一切"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "筆電這輩子沒關過", OptionB: "每晚必關機"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "寫 Code 追求優雅", OptionB: "寫 Code 會跑就好"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "注重專案結構", OptionB: "一鍋燉流派"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "熱愛開會討論", OptionB: "恨不得所有會議都取消"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "下班立刻斷開連結", OptionB: "隨時監控 Slack"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "重視工作生活平衡", OptionB: "工作就是我的生活"},

		// 娛樂與社交類
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "演唱會錄影派", OptionB: "現場投入派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "看電影必吃爆米花", OptionB: "看電影專心看到忘記吃"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "去 KTV 當歌霸", OptionB: "去 KTV 專心吃"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "桌遊主辦人", OptionB: "桌遊被揪客"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "喜歡滑雪散步", OptionB: "喜歡極限運動"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "打電動會爆粗口", OptionB: "佛系玩家心平氣和"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "動漫宅", OptionB: "美劇迷"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "體育現場看", OptionB: "在家看直播"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "熱愛排隊名店", OptionB: "看到排隊就放棄"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "喜歡恐怖遊戲", OptionB: "只敢玩益智遊戲"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "手遊課金派", OptionB: "無課金肝帝"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "酒吧喝酒聊是非", OptionB: "夜店跳舞到天亮"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "社群平台瘋狂發文", OptionB: "萬年潛水員"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "喜歡多人連線", OptionB: "堅持單機模式"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "電影看一次就懂", OptionB: "三刷才看細節"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "喜歡文藝展覽", OptionB: "喜歡熱鬧市集"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "旅遊狂拍照", OptionB: "旅遊用心感受"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "假日睡到中午", OptionB: "假日早起晨跑"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "相信童話故事", OptionB: "現實主義崩壞派"},
		{Category: "entertainment", Question: "世界上只有兩種人", OptionA: "跨年去現場擠", OptionB: "跨年在家看電視轉播"},

		// 綜合創意類
		{Category: "general", Question: "世界上只有兩種人", OptionA: "襪子要成對", OptionB: "襪子隨便穿"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "杯子要有蓋子", OptionB: "直接開口杯"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "購物車塞滿不買", OptionB: "看到喜歡秒下單"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡冬天", OptionB: "喜歡夏天"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "剪頭髮會跟髮型師聊天", OptionB: "剪頭髮全程安靜"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "洗澡會唱歌", OptionB: "洗澡發呆思考人生"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "下雨天穿雨衣", OptionB: "下雨天撐雨傘"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "早餐一定要吃", OptionB: "早餐不吃派"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "習慣喝茶", OptionB: "喜歡喝咖啡"},

		// --- 擴充第二部分 (201-350) ---
		// 旅遊類 (新分類)
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "喜歡去海邊", OptionB: "喜歡去山上"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "住飯店派", OptionB: "住露營/民宿派"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "整理行李一週前", OptionB: "出發前一小時才收"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "喜歡自由行", OptionB: "喜歡跟團"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "出國必買紀念品", OptionB: "空手而歸派"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "搭飛機選靠窗", OptionB: "搭飛機選靠走道"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "會帶自己的盥洗用品", OptionB: "用飯店提供的就好"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "喜歡自駕遊", OptionB: "喜歡搭大眾運輸"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "喜歡去熱熱的地方", OptionB: "喜歡去冷冷的國家"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "護照隨身帶", OptionB: "護照鎖在保險箱"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "會把盥洗小樣帶回家", OptionB: "絕對不拿飯店備品"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "洗照片做相簿", OptionB: "照片永遠在硬碟裡"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "喜歡深度遊一地", OptionB: "喜歡打卡多個景點"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "會為了美食去旅行", OptionB: "會為了建築景觀去旅行"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "喜歡逛免稅店", OptionB: "直接去登機門"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "喜歡紅眼航班", OptionB: "堅持正常作息航班"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "會查當地文化禁忌", OptionB: "隨機應變派"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "喜歡一個人旅行", OptionB: "喜歡有人陪"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "旅行回來要休息三天", OptionB: "隔天立刻能上班"},
		{Category: "travel", Question: "世界上只有兩種人", OptionA: "會買當地特色衣服穿", OptionB: "堅持穿平常的衣服"},

		// 社交與人際類 (加強)
		{Category: "social", Question: "世界上只有兩種人", OptionA: "遲到五分鐘是常態", OptionB: "提早五分鐘是尊重"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "講電話派", OptionB: "傳簡訊派"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "聚會帶頭糾團", OptionB: "負責出現在那裡"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "第一次見面就自來熟", OptionB: "要熟很久才敢講話"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "朋友圈很廣但淺", OptionB: "知心好友只有兩三個"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "會記得別人的生日", OptionB: "需要 FB 提醒"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "在路上看到熟人主動打招呼", OptionB: "裝作沒看到低頭滑手機"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "聚餐後會主動說拆帳", OptionB: "等人開口再給錢"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "喜歡講笑話逗人開心", OptionB: "負責笑的那一個"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "分手後還能當朋友", OptionB: "分手後老死不相往來"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "會對服務生說謝謝", OptionB: "點完餐就完事了"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "喜歡參加婚禮", OptionB: "覺得婚禮很麻煩"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "訊息顯示已讀是基本禮貌", OptionB: "已讀不回是自由"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "喜歡稱讚別人", OptionB: "不習慣說肉麻話"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "相信一見鍾情", OptionB: "相信日久生情"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "生氣時會沈默不語", OptionB: "生氣時會大聲爭執"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "喜歡當聽眾", OptionB: "喜歡當說話的人"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "會主動幫人開門", OptionB: "自己過完就好"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "對讚美感到害羞", OptionB: "大方接受讚美"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "在意別人的看法", OptionB: "走自己的路"},

		// 數位生活與行為類
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "螢幕截圖派", OptionB: "另存圖片派"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "Google 地圖用衛星視圖", OptionB: "Google 地圖用標準視圖"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "網頁連結用新分頁開啟", OptionB: "直接原視窗開啟"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "桌面上放一個資源回收桶", OptionB: "回收桶藏起來或刪除"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "手機手電筒開著不自知", OptionB: "用完立刻關掉"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "看影片會快轉", OptionB: "一秒都不漏看"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "會在影片下留言", OptionB: "純看片不參與討論"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "喜歡整理雲端硬碟目錄", OptionB: "東西全丟在根目錄"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "聽 Spotify", OptionB: "聽 Apple Music"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "習慣用 Dark Mode", OptionB: "習慣用 Light Mode"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "對 App 權限斤斤計較", OptionB: "一律按允許"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "每天都會清空垃圾信箱", OptionB: "放任它累積到幾萬封"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "會給 App 評分", OptionB: "萬年跳過對話框"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "追蹤上千個網紅", OptionB: "只追蹤認識的朋友"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "會用數位標籤管理檔案", OptionB: "用檔名來管理"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "視訊背景是虛擬特效", OptionB: "大方露出真實房間"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "打字習慣用全形符號", OptionB: "打字習慣用半形符號"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "電子表格愛好者", OptionB: "筆記本畫表格派"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "有在經營個人部落格或頻道", OptionB: "純當讀者或觀眾"},
		{Category: "digital", Question: "世界上只有兩種人", OptionA: "會定時更新韌體", OptionB: "萬年無視更新通知"},

		// 心理與習慣進度題
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "擠牙膏從最前面擠", OptionB: "擠牙膏會慢慢往上擼"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "穿襪子先穿左腳", OptionB: "穿襪子先穿右腳"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "洗頭用兩遍洗髮精", OptionB: "一遍搞定派"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "煮泡麵分兩鍋水去油", OptionB: "一鍋到底最香派"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "吃飯時會配影片", OptionB: "專心吃飯不分心"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "習慣戴手錶", OptionB: "習慣裸機手腕"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "垃圾隨手分類", OptionB: "最後一刻再說派"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "回家第一件事是洗手", OptionB: "回家第一件事是躺下"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "習慣坐火車補眠", OptionB: "坐車一定要看窗外"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "吃完飯立刻洗碗", OptionB: "碗筷在水槽泡一夜"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "喜歡香皂洗澡", OptionB: "喜歡沐浴乳洗澡"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "睡覺一定要抱抱枕", OptionB: "雙手放在肚子上睡"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "進門先換室內鞋", OptionB: "赤腳在家走"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "出門前檢查瓦斯電源三次", OptionB: "門鎖上就走人"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "用毛巾擦臉", OptionB: "用洗臉巾或手捧水"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "習慣用左手刷牙(非慣用手)", OptionB: "慣用手派"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "喝水用固定杯子", OptionB: "哪個杯子近用哪個"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "包包裡有備用電池/行動電源", OptionB: "生死有命富貴在天"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "會收集超商點數", OptionB: "點數是什麼能吃嗎"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "喜歡喝燙口咖啡", OptionB: "喜歡放涼再喝"},

		// 運動與健康類
		{Category: "health", Question: "世界上只有兩種人", OptionA: "健身房重訓派", OptionB: "戶外慢跑派"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "每天量體重", OptionB: "這輩子不想知道體重"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "生病先看中醫", OptionB: "生病先看西醫"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "喜歡吃生菜沙拉", OptionB: "菜一定要吃熟的"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "爬樓梯消耗熱量", OptionB: "死都要等電梯"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "每天喝足 2000cc 水", OptionB: "靠含糖飲料維持生命"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "睡眠充足 8 小時", OptionB: "精修熬夜 4 小時"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "會看營養標示", OptionB: "好吃才是重點"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "注重防曬", OptionB: "享受日光浴"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "拉筋派", OptionB: "身體僵硬派"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "喜歡瑜珈或皮拉提斯", OptionB: "喜歡籃球或足球"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "會定時健康檢查", OptionB: "感覺不對才去醫院"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "家裡有健身器材當衣架", OptionB: "器材真的有在用"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "喜歡吃水果當零食", OptionB: "喜歡吃洋芋片當零食"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "戴著計步器走路", OptionB: "不想知道走了多少"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "站著工作派", OptionB: "坐著工作派"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "下班後去運動", OptionB: "下班後去睡覺"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "相信保健食品有用", OptionB: "天然食物派"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "喜歡冷水澡挑戰", OptionB: "絕對熱水派"},
		{Category: "health", Question: "世界上只有兩種人", OptionA: "口罩掛在下巴", OptionB: "口罩戴得緊緊"},

		// 綜合創意三
		{Category: "general", Question: "世界上只有兩種人", OptionA: "鉛筆盒要整整齊齊", OptionB: "筆全部散在包包裡"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "書套愛好者", OptionB: "裸書派"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡看電子地圖", OptionB: "喜歡看路牌指示"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "說話很快", OptionB: "說話慢吞吞"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "對灰塵很敏感", OptionB: "只要沒髒到不能坐就沒事"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "網購會貨比三家", OptionB: "看到第一家便宜就下單"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "衣服標籤一定要剪掉", OptionB: "穿到標籤爛掉也無所謂"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "會把發票存載具", OptionB: "喜歡拿實體紙本"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "習慣用現金付款", OptionB: "沒手機不能活(電子支付)"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "相信外星人", OptionB: "務實主義地球人"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "出門會噴香水", OptionB: "原味才是真我"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡吃糖醋排骨", OptionB: "喜歡吃蔥爆牛肉"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "過年會發紅包", OptionB: "期待領紅包的年紀"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "有在收集特定公仔", OptionB: "斷捨離狂熱者"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡喝珍珠奶茶的手搖飲", OptionB: "喜歡喝原萃茶"},

		// --- 擴充最終部分 (351-500) ---
		// 學習與成長類 (新分類)
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "讀書喜歡做筆記", OptionB: "讀書只用眼睛看"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "喜歡文科(文史哲)", OptionB: "喜歡理科(數理化)"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "線上課程愛好者", OptionB: "實體講座愛好者"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "習慣早上讀書", OptionB: "習慣深夜讀書"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "喜歡舉手發問", OptionB: "默默坐在角落聽"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "考前突擊派", OptionB: "平時積累派"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "喜歡教別人東西", OptionB: "喜歡聽別人教"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "會重複看同一本書", OptionB: "看過一遍就夠了"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "學習時需要絕對安靜", OptionB: "學習時喜歡背景白噪音"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "相信天賦決定一切", OptionB: "相信努力能補拙"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "喜歡看紀錄片", OptionB: "實用工具書派"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "會參加讀書會", OptionB: "獨自學習派"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "對新事物充滿好奇", OptionB: "守著已知的領域"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "習慣用圖表理解資訊", OptionB: "習慣用文字理解資訊"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "會去圖書館", OptionB: "喜歡在咖啡廳讀書"},

		// 理財與消費類 (新分類)
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "每筆帳必記", OptionB: "錢花哪去都不知道"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "積極投資派(股票/虛擬幣)", OptionB: "保守儲蓄派(定存)"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "刷卡拿回饋", OptionB: "付現最踏實"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "百貨公司週年慶必衝", OptionB: "缺什麼才買什麼"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "買東西喜歡殺價", OptionB: "標價多少給多少"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "會買保險買個安心", OptionB: "覺得保險是騙錢"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "有備用緊急預算", OptionB: "月光族萬歲"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "喜歡買名牌包/錶", OptionB: "高CP值平價好物派"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "會設定每月預算上限", OptionB: "刷到卡不過為止"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "相信理財師的建議", OptionB: "只相信自己的直覺"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "會領取各種優惠券", OptionB: "嫌麻煩懶得領"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "注重退休規劃", OptionB: "今朝有酒今朝醉"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "買房產保值", OptionB: "租房生活比較自由"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "會分期付款減輕壓力", OptionB: "一律一次付清"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "對發票是假日娛樂", OptionB: "發票不知散落何處"},

		// 交通與通勤類 (新分類)
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "搭捷運選有位子坐", OptionB: "選靠近下車站門口站著"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "開車不超速安全第一", OptionB: "超速五公里內是標準"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "騎機車戴全罩安全帽", OptionB: "西瓜皮帥氣就好"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "搭公車會看風景", OptionB: "上車立刻昏睡"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "開車會碎碎念前方車輛", OptionB: "佛系駕駛不慍不火"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "會提早出門預防塞車", OptionB: "精準算好最後一刻"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "喜歡騎腳踏車通勤", OptionB: "除了走路以外都要引擎"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "導航說轉就轉", OptionB: "我比較相信自己的方向感"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "搭高鐵選對號座", OptionB: "自由座省錢派"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "會讓位給需要的人", OptionB: "低頭滑手機假裝沒看到"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "喜歡搭 Uber/計程車", OptionB: "堅持搭大眾運輸"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "會記住常用的捷運車廂號碼", OptionB: "哪裡有門哪裡進"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "停車一定要停在正中間", OptionB: "有進格子就好"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "喜歡夜間開車", OptionB: "夜晚視線不好不敢開"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "會把車子洗得亮晶晶", OptionB: "下雨就是我的自動洗車"},

		// 季節與節慶類 (新分類)
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "過生日要大肆慶祝", OptionB: "生日只想平淡度過"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "聖誕節要交換禮物", OptionB: "覺得交換禮物很浪費錢"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "過年必看春晚/特別節目", OptionB: "過年都在補眠/打電動"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "萬聖節會裝扮", OptionB: "萬聖節關我什麼事"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "情人節必花大錢吃大餐", OptionB: "情人節回家煮泡麵"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "喜歡逛年貨大街", OptionB: "害怕人擠人躲在家"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "中秋節必烤肉", OptionB: "中秋節純賞月吃月餅"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "元旦要衝第一道曙光", OptionB: "元旦要睡飽迎接新的一年"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "相信聖誕老人存在過(傳說)", OptionB: "從小就很務實不信這套"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "會寄手寫賀卡", OptionB: "傳個貼圖代表心意"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "喜歡夏天去游泳", OptionB: "夏天只想冷氣防守"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "冬天必吃火鍋", OptionB: "冬天也要吃冰淇淋"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "喜歡雨天的浪漫", OptionB: "下雨天只想不出門"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "會為了追花季跑遍全台", OptionB: "路邊的小花就很美"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "熱愛路跑活動", OptionB: "馬拉松是外星人的運動"},

		// 瑣碎生活類 (新分類)
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "鑰匙掛在腰間", OptionB: "鑰匙放在深不見底的包包"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "手機指紋解鎖", OptionB: "手機人臉/動態解鎖"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "筆寫完蓋子必蓋好", OptionB: "蓋子常常失蹤"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "吃飯必拿衛生紙墊著", OptionB: "直接開吃灑出來再說"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "喜歡買各種顏色原子筆", OptionB: "一隻黑筆打天下"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "對品牌有忠誠度", OptionB: "誰特價買誰"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "家裡備有急救箱", OptionB: "受傷等它自己好"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "會把衣服按顏色分類掛", OptionB: "手摸到哪件穿哪件"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "睡覺一定要全黑", OptionB: "沒留點光沒安全感"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "會摺紙盒放骨頭渣", OptionB: "直接吐在衛生紙或桌上"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "喜歡香氛蠟燭", OptionB: "對氣味過敏派"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "會收集電影票根", OptionB: "出電影院就丟垃圾桶"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "喜歡手寫日記", OptionB: "數位日記愛好者"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "習慣用環保餐具", OptionB: "方便萬歲用免洗"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "相信命運是天注定", OptionB: "我命由我不由天"},

		// 剩餘補齊
		{Category: "food", Question: "世界上只有兩種人", OptionA: "喜歡吃鹹豆漿", OptionB: "鹹豆漿是異教徒"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "雞蛋吃全熟", OptionB: "雞蛋吃半熟流心"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "喜歡美式咖啡", OptionB: "喜歡拿鐵/摩卡"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃拉麵必喝湯", OptionB: "拉麵湯頭太鹹只吃麵"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "火鍋不沾醬", OptionB: "沾醬才是火鍋的靈魂"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "每天早起都要喝熱水", OptionB: "起床第一口冰水才清醒"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "洗澡會洗耳朵後面", OptionB: "洗澡略過派"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "修剪鼻毛很勤勞", OptionB: "鼻毛外露不自覺"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "喜歡二合一筆電", OptionB: "堅持平板與電腦分開"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "電腦有專屬防塵蓋", OptionB: "滿是指紋灰塵"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "很在意公平正義", OptionB: "凡事利益優先"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡規律的生活", OptionB: "討厭一層不變"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "會在履歷上吹牛", OptionB: "老實交代實力"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "喜歡在安靜的環境工作", OptionB: "需要聽喧鬧聲才有感"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "是群組裡的發起者", OptionB: "是群組裡的已讀不回者"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "說話時會看對方眼睛", OptionB: "說話時眼睛看地板"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "相信未來會更好", OptionB: "擔憂世界末日"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡貓也喜歡狗", OptionB: "對寵物無感"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "是個愛乾淨的人", OptionB: "覺得亂也是一種美"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "重視名聲", OptionB: "重視財富"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "這是一個有趣的問題", OptionB: "快點結束這個問題吧"},

		// --- 最後補齊 (總計 500) ---
		{Category: "food", Question: "世界上只有兩種人", OptionA: "火鍋一定要加芋頭", OptionB: "芋頭在火鍋裡是詛咒"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃雞塊沾砂糖", OptionB: "雞塊沾砂糖是邪教"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "拉麵要吃硬麵", OptionB: "拉麵要吃軟麵"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "巧克力喜歡苦的", OptionB: "巧克力喜歡甜的"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "披薩邊邊會吃掉", OptionB: "披薩邊邊丟掉"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "喝可樂分不出零卡", OptionB: "零卡可樂味道很怪"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃麵一定要有湯", OptionB: "乾麵派"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "三明治去邊", OptionB: "三明治連邊吃"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "熱狗加芥末", OptionB: "熱狗只加番茄醬"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吐司烤到焦脆", OptionB: "吐司微熱就好"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "洗臉用冷水", OptionB: "洗臉用溫水"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "睡覺會磨牙", OptionB: "睡覺安靜如貓"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "出門必檢查包包兩次", OptionB: "拿了包就走"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "衣服穿一次就洗", OptionB: "沒味道就能繼續穿"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "習慣用手帕", OptionB: "習慣用面紙"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "看書會跳著看", OptionB: "逐字讀完"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "洗澡會順便刷牙", OptionB: "刷牙洗澡分開"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "剪指甲剪很深", OptionB: "留一點白邊"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "東西用完歸位", OptionB: "東西用完隨手放"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "睡覺四肢縮起來", OptionB: "睡覺大字型"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "電腦桌布是預設", OptionB: "電腦桌布是自定義圖片"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "會設定密碼定期更改", OptionB: "一組密碼用十年"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "手機藍芽永遠開著", OptionB: "要用才開"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "喜歡曲面螢幕", OptionB: "喜歡平面螢幕"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "電腦有裝防毒軟體", OptionB: "全靠裸奔與直覺"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "會清理瀏覽紀錄", OptionB: "紀錄留著當回憶"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "喜歡小手機", OptionB: "螢幕越大越好"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "常用快捷鍵", OptionB: "全程滑鼠流"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "鍵盤有 RGB 燈", OptionB: "低調單色燈或無燈"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "手機螢幕貼有裂痕繼續用", OptionB: "有一絲裂痕立刻換"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "相信人性本善", OptionB: "相信人性本惡"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "做決定很果斷", OptionB: "猶豫不決糾結很久"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡給予建議", OptionB: "喜歡安靜傾聽"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "重視名譽勝過金錢", OptionB: "財富才是硬道理"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "會主動道歉", OptionB: "死不認錯派"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "喜歡冒險", OptionB: "追求安穩"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "說話幽默風趣", OptionB: "說話實話實說"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "會為了理想奮不顧身", OptionB: "務實面對現實"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "容易害羞紅臉", OptionB: "面不改色大心臟"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "活在當下", OptionB: "規劃未來"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "上班前先喝咖啡", OptionB: "上班後被氣到喝咖啡"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "喜歡在早上開會", OptionB: "早上只適合發呆"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "筆電貼滿貼紙", OptionB: "乾乾淨淨派"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "會設定工作番茄鐘", OptionB: "憑感覺工作"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "喜歡開放式辦公室", OptionB: "喜歡隔間"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "會幫同事訂午餐", OptionB: "午餐獨自解決"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "下班後不看工作群組", OptionB: "隨時掛在線上"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "工作時穿得很正式", OptionB: "穿得很休閒"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "會寫工作日誌", OptionB: "想不起來昨天做了什麼"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "追求完美主義", OptionB: "及格萬歲派"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "喜歡發朋友圈紀錄生活", OptionB: "生活是用來過的不是發文的"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "會主動幫陌生人拍照", OptionB: "看到有人拍照趕快避開"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "喜歡熱鬧的派對", OptionB: "小聚會比較舒適"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "會記得紀念日並換慶祝", OptionB: "那天就是普通的一天"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "對朋友掏心掏肺", OptionB: "君子之交淡如水"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "會主動破冰", OptionB: "等別人來跟我說話"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "相信患難見真情", OptionB: "相信利聚而散"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "喜歡跟長輩聊天", OptionB: "跟同齡人比較自在"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "會給陌生人微笑", OptionB: "酷酷冷漠臉"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "說話大聲熱情", OptionB: "溫柔細聲"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "搭車會跟司機聊天", OptionB: "全程不發一言"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "開車會聽廣播", OptionB: "開車聽自己的清單"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "摩托車會換酷炫排氣管", OptionB: "安安靜靜最美"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "喜歡搭火車旅行", OptionB: "火車太慢了我選高鐵"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "開車很守規矩", OptionB: "路是我家開的"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "騎單車會戴安全帽", OptionB: "隨風飄逸派"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "停車一次到位", OptionB: "嚕五次才進位"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "喜歡步行的感覺", OptionB: "能坐車絕不走路"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "會禮讓後方超車", OptionB: "擋住你的路是我的樂趣"},
		{Category: "transport", Question: "世界上只有兩種人", OptionA: "喜歡車內香氛", OptionB: "自然風最好"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "喜歡學外語", OptionB: "中文學好就很了不起了"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "相信活到老學到老", OptionB: "畢業那天就是學習的終點"},
		{Category: "learning", Question: "世界上指導只有兩種人", OptionA: "喜歡看教學影片", OptionB: "喜歡看說明書/文字文件"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "會主動分享所學", OptionB: "私藏秘笈派"},
		{Category: "learning", Question: "世界上只有兩種人", OptionA: "喜歡參加線上黑客松", OptionB: "那種活動太累了不去"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "領薪水立刻轉存定存", OptionB: "領薪水先去吃大餐"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "會用信用卡積分換機票", OptionB: "積分過期了都不知道"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "相信定期定額", OptionB: "相信單筆梭哈"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "買東西會看成分表", OptionB: "便宜就好不看成分"},
		{Category: "finance", Question: "世界上只有兩種人", OptionA: "會給小費表達感謝(非強制地區)", OptionB: "按照法條/帳單給錢"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "跨年一定要倒數", OptionB: "九點就上床睡覺"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "聖誕裝飾十一月就擺", OptionB: "聖誕節當天才掛"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "喜歡放鞭炮鬧中秋", OptionB: "討厭煙霧瀰漫"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "除夕夜要領紅包", OptionB: "除夕夜要發紅包"},
		{Category: "holidays", Question: "世界上只有兩種人", OptionA: "喜歡熱鬧的慶典型態", OptionB: "喜歡寧靜的文化巡禮"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "襪子不見了會去找", OptionB: "不見了就買新的"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "會把發票整理好", OptionB: "發票塞在口袋或包包深處"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "喜歡收集郵票/紙鈔", OptionB: "覺得那些只是錢"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "會對機器說謝謝", OptionB: "這只是機器不需要溝通"},
		{Category: "trivial", Question: "世界上只有兩種人", OptionA: "相信星座", OptionB: "相信科學"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "你是 A 派", OptionB: "你是 B 派"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡看日出", OptionB: "喜歡看夕陽"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡夏天", OptionB: "喜歡冬天"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "相信奇蹟", OptionB: "相信腳踏實地"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡冒險", OptionB: "喜歡規律"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "注重過程", OptionB: "注重結果"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "追求完美", OptionB: "得過且過"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "熱愛生活", OptionB: "感慨人生"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "很有耐心", OptionB: "急性子"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡挑戰", OptionB: "喜歡安逸"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "重視靈感", OptionB: "重視邏輯"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "很有自律", OptionB: "自由散慢"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "樂於助人", OptionB: "獨善其身"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "心中有夢", OptionB: "腳下有路"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "喜歡閱讀", OptionB: "喜歡實踐"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "重視外表", OptionB: "重視內涵"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "很有創意", OptionB: "守規矩"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "樂觀向上", OptionB: "悲觀思考"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "善於表達", OptionB: "拙於言詞"},
		{Category: "general", Question: "世界上只有兩種人", OptionA: "最後一題選我", OptionB: "不，選我！"},

		// --- 2026 最新擴充題目 (湊滿 600+ 題) ---
		// 1. 殘酷極限二選一 (Question: 殘酷極限二選一，你會選哪個？)
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "忍受不吃飯 3 天", OptionB: "忍受不睡覺 1 天"},
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "這輩子只能用手抓東西吃", OptionB: "這輩子只能用吸管吃所有食物"},
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "夏天高溫 38 度只能吃熱燙火鍋", OptionB: "冬天寒流 5 度只能吃大剉冰"},
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "這輩子再也不能上網", OptionB: "這輩子再也不能聽音樂"},
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "出門路上永遠不會塞車", OptionB: "去任何熱門名店永遠不用排隊"},
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "月薪多 3 萬但每天加班到半夜", OptionB: "每天準時下班但薪水剛好夠過活"},
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "這輩子只能看喜劇片", OptionB: "這輩子只能看懸疑恐怖片"},
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "失去味覺但身材完美", OptionB: "保有味覺但吃什麼都發胖"},
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "一輩子穿不成對的襪子", OptionB: "一輩子穿有些許破洞的襪子"},
		{Category: "extreme", Question: "殘酷極限二選一，你會選哪個？", OptionA: "永遠只能喝溫水", OptionB: "永遠只能喝冰水"},

		// 2. 超能力與夢幻選擇 (Question: 世界上只有兩種人)
		{Category: "superpower", Question: "世界上只有兩種人", OptionA: "擁有私人頂級大廚", OptionB: "擁有私人全能管家"},
		{Category: "superpower", Question: "世界上只有兩種人", OptionA: "穿越到 100 年前的過去生活一年", OptionB: "穿越到 100 年後的未來生活一年"},
		{Category: "superpower", Question: "世界上只有兩種人", OptionA: "擁有永遠不會變胖的體質", OptionB: "擁有永遠不需要睡覺的精力"},
		{Category: "superpower", Question: "世界上只有兩種人", OptionA: "獲得能力：隨時秒睡且睡超香", OptionB: "獲得能力：吃任何美食都不會蛀牙胃痛"},
		{Category: "superpower", Question: "世界上只有兩種人", OptionA: "擁有能跟動物對話的能力", OptionB: "擁有能精通世界上所有語言的能力"},
		{Category: "superpower", Question: "世界上只有兩種人", OptionA: "獲得隨時隱形的能力（不能說話）", OptionB: "獲得隨時飛天的能力（速度跟走路一樣慢）"},
		{Category: "superpower", Question: "世界上只有兩種人", OptionA: "能瞬間移到去過的任何地方", OptionB: "能隨時召喚出想吃的任何食物"},
		{Category: "superpower", Question: "世界上只有兩種人", OptionA: "過目不忘但偶爾會忘記名字", OptionB: "過目即忘但直覺無敵敏銳"},

		// 3. 超生活化：飲食習慣對決 (Question: 世界上只有兩種人)
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃鹹酥雞一定要加九層塔", OptionB: "鹹酥雞只要胡椒鹽派"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃粉漿蛋餅一定要加醬油膏", OptionB: "蛋餅只沾番茄醬或甜辣醬"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "牛肉麵一定要加酸菜加醋", OptionB: "牛肉麵堅持喝原味濃郁湯頭"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃熱湯麵會大口吸麵發出聲音", OptionB: "吃麵安靜吃絕對不能發出聲音"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "喝手搖飲全加料（珍珠粉條椰果）", OptionB: "完全不加料（純茶或純奶茶）"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃便當一定要把最喜歡的菜留到最後", OptionB: "第一口就先吃最喜歡的菜"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "喝咖啡堅持只喝黑咖啡或美式", OptionB: "一定要加牛奶或糖的拿鐵派"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃水果堅持削皮切塊拿叉子吃", OptionB: "水果洗乾淨直接整顆啃"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃火鍋醬料一定要加沙茶醬", OptionB: "火鍋醬料只加清淡醬油蔥花"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "烤肉最喜歡吃烤肉片夾吐司", OptionB: "烤肉只單吃肉不夾吐司"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃涼麵一定要加爆麻醬", OptionB: "涼麵偏好清爽醋香風味"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃生魚片一定要蘸超多哇沙米", OptionB: "生魚片只蘸一點點醬油"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃炸雞一定要撕皮分開吃", OptionB: "炸雞連皮帶肉大口咬"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "熱湯端上來立刻趁熱大口喝", OptionB: "熱湯一定要吹涼才敢入口"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "買手搖飲一定要點半糖以上", OptionB: "手搖飲永遠只點微糖或無糖"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃洋芋片一定要用衛生紙或夾子拿", OptionB: "洋芋片直接上手吃完再舔手指"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "喝汽水最愛享受打嗝的爽快感", OptionB: "喝汽水努力憋著不打嗝"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "白飯一定要淋滿湯汁肉汁", OptionB: "白飯堅持要乾淨乾爽"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃麥當勞大薯要擠在紙盒上沾醬", OptionB: "醬直接擠在托盤紙上沾"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃小籠包一定要先咬破吸湯汁", OptionB: "小籠包一口整顆塞進嘴裡"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "壽司最愛吃生鮮鮭魚鮪魚", OptionB: "壽司最愛吃炙燒或熟食類"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "喝牛奶只喝鮮乳全脂", OptionB: "只喝低脂或植物奶燕麥奶"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃乾麵一定要加辣油或辣醬", OptionB: "乾麵原味最讚拒絕任何辣"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "吃雞蛋糕一定要買有餡料的", OptionB: "雞蛋糕只買古早味無餡料的"},
		{Category: "food", Question: "世界上只有兩種人", OptionA: "夏天冰品最愛古早味剉冰", OptionB: "夏天冰品最愛雪花冰或義式冰淇淋"},

		// 4. 超生活化：日常習慣與行為 (Question: 世界上只有兩種人)
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "鬧鐘設定 1 個就立刻起床", OptionB: "鬧鐘設定 5 個以上才爬得起來"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "手機剩 1% 電量依然淡定", OptionB: "手機低於 20% 就焦慮爆表"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "看影片追劇一定要開啟字幕", OptionB: "看影片不需要字幕"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "聽音樂一定要看歌詞", OptionB: "聽音樂純粹聽旋律"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "一個人去餐廳內用完全不尷尬", OptionB: "一個人去餐廳絕對外帶回家吃"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "結帳為了湊整數算得很精（掏510找300）", OptionB: "直接拿千元大鈔找一堆零錢"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "夏天洗澡堅持要洗熱水澡", OptionB: "夏天洗澡一定要洗冷水澡才爽"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "睡覺環境必須絕對全黑才睡得著", OptionB: "睡覺必須留小夜燈或有點光"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "出國前幾天就把詳細行程排滿滿", OptionB: "到當地隨興看心情走"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "發訊息如果對方已讀不回會很介意", OptionB: "已讀不回很正常自己也常這樣"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "下雨天出門一定要穿雨鞋/防水鞋", OptionB: "下雨天直接穿拖鞋涼鞋踩水"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "包包裡永遠備有折疊傘與面紙", OptionB: "兩手空空出門需要再買"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "習慣用手機行事曆提醒所有行程", OptionB: "靠大腦記憶或手寫紙本記事"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "大眾運輸一上車立刻戴耳機放音樂", OptionB: "戴耳機不放聲音或純聽環境音"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "看書或看文章喜歡快速掃視大意", OptionB: "堅持逐字逐句細細閱讀"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "拍照時永遠站最旁邊或最後面", OptionB: "拍照時自然站 C 位中央"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "出門前鞋子一定要刷得乾乾淨淨", OptionB: "鞋子只要沒破爛就繼續穿"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "洗完澡立刻用吹風機把頭髮吹全乾", OptionB: "洗完澡包著頭巾等它半乾才吹"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "手機響起第一時間立刻接聽", OptionB: "看到陌生電話先等它響完再查號碼"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "房間衣服收納一定要用衣服架掛好", OptionB: "衣服全部摺好堆在櫃子或椅子上"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "買保養品彩妝品只買固定愛用品牌", OptionB: "熱愛嘗試各種新品與開箱試用"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "習慣把發票存入手機條碼載具", OptionB: "喜歡拿實體紙本發票享受對獎感"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "看Youtube影片習慣用 1.5倍速播放", OptionB: "看Youtube影片堅持原速播放"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "每次打掃衛生一定要用吸塵器加拖地", OptionB: "看到哪裡髒才順手掃哪裡"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "喜歡自己下廚煮飯享受料理過程", OptionB: "外食族或外送平台忠實用戶"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "戴手錶只戴傳統機械錶或指針錶", OptionB: "戴手錶只戴智慧手錶手環"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "皮夾鑰匙手機永遠放在固定口袋或位置", OptionB: "每次要出門都在全家找手機鑰匙"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "坐沙發時一定要盤腿或抱著枕頭", OptionB: "坐沙發端端正正腳放地上"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "坐飛機高鐵喜歡選靠窗看風景", OptionB: "坐飛機高鐵喜歡選靠走道方便進出"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "去超商買東西一定會跟店員說謝謝", OptionB: "拿了東西結完帳點頭離開"},

		// 5. 超生活化：個人性格、社交與生活哲學 (Question: 世界上只有兩種人)
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "當全世界最醜的天才", OptionB: "當全世界最漂亮的智障"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "另一半醜陋但對你極度專一", OptionB: "另一半帥美到爆但極度花心"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "手機網路永遠龜速", OptionB: "手機電量永遠只有 1%"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "聊天只傳文字訊息", OptionB: "聊天最愛傳長語音訊息"},
		{Category: "tech", Question: "世界上只有兩種人", OptionA: "瀏覽器分頁開到幾百個都不關", OptionB: "看完一個頁面立刻關閉"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "聽到諧音梗會秒笑並開始接下句", OptionB: "聽到諧音梗只會翻白眼或無奈"},
		{Category: "habit", Question: "世界上只有兩種人", OptionA: "買東西看到特價買一送一就忍不住買", OptionB: "只買眼前剛好需要用到的東西"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "在路上看到熟人會主動揮手打招呼", OptionB: "在路上看到熟人裝作沒看到滑手機避開"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "遇到不爽的事會當下說出來", OptionB: "遇到不爽的事會先忍著回家崩潰"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "聚餐聊天時永遠是主導話題的人", OptionB: "聚餐聊天時永遠是微笑聽眾"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "決定一件事情非常果斷不悔恨", OptionB: "做決定猶豫不決選完又後悔"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "喜歡在社群媒體分享生活動態", OptionB: "萬年不發文純粹當潛水觀眾"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "看感人電影會眼淚流不停", OptionB: "看感人電影內心毫無波瀾"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "生日喜歡大張旗鼓跟一群人慶祝", OptionB: "生日喜歡低調一個人或跟最親密的人過"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "東西弄丟了會瘋狂找尋直到找到", OptionB: "東西弄丟了找三分鐘就放棄買新的"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "遇到挫折會馬上化悲憤為力量", OptionB: "遇到挫折需要一個人靜靜躲起來"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "上班工作習慣聽流行音樂放鬆", OptionB: "上班工作需要絕對安靜環境才能思考"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "開會時習慣積極提出問題與建議", OptionB: "開會時希望會議越快結束越好"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "工作進度喜歡提早幾天完成", OptionB: "工作進度不到最後一刻絕不動手"},
		{Category: "work", Question: "世界上只有兩種人", OptionA: "電腦桌面整理得一塵不染", OptionB: "電腦桌面擺滿各種暫存檔案與資料夾"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "跟朋友聚會一定要拍照留念", OptionB: "跟朋友聚會開心就好從不拍照"},
		{Category: "social", Question: "世界上只有兩種人", OptionA: "約會聚餐永遠提早 5 到 10 分鐘抵達", OptionB: "約會聚餐永遠剛好或壓線抵達"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "相信幸運色與星座運勢", OptionB: "堅信事在人為不信命理"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "遇到吵架會想當場理清溝通清楚", OptionB: "遇到吵架會選擇冷靜冷處理"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "熱愛收藏公仔玩具周邊商品", OptionB: "追求極簡斷捨離家裡不留雜物"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "習慣把願望與目標大聲說出來", OptionB: "習慣默默努力做成了才說"},
		{Category: "personality", Question: "世界上只有兩種人", OptionA: "享受挑戰未知的興奮感", OptionB: "享受一切盡在掌握中的安全感"},
	}
}

// ConvertToGameQuestions 將2種人題目轉換為遊戲題目格式
func ConvertToGameQuestions(twoTypesQuestions []TwoTypesQuestion) []models.Question {
	questions := make([]models.Question, len(twoTypesQuestions))
	
	for i, q := range twoTypesQuestions {
		questions[i] = models.Question{
			ID:           i + 1,
			QuestionText: q.Question,
			OptionA:      q.OptionA,
			OptionB:      q.OptionB,
			Category:     q.Category,
			TimesUsed:    0,
			IsActive:     true,
			CreatedAt:    time.Now(),
		}
	}
	
	return questions
}

// GetRandomQuestions 隨機選取指定數量的題目
func GetRandomQuestions(count int) []models.Question {
	allQuestions := ConvertToGameQuestions(GetTwoTypesQuestions())
	
	if count >= len(allQuestions) {
		return allQuestions
	}
	
	// 隨機打亂題目順序
	rand.Seed(time.Now().UnixNano())
	for i := len(allQuestions) - 1; i > 0; i-- {
		j := rand.Intn(i + 1)
		allQuestions[i], allQuestions[j] = allQuestions[j], allQuestions[i]
	}
	
	return allQuestions[:count]
}